#spring elasticsearch
spring:
  data:
    elasticsearch:
      cluster-nodes: 10.10.10.34:9300
      cluster-name: es-testevn
      repositories:
        enabled: false
      properties:
        transport.tcp.connect_timeout : 120s

index:
  name: index_demo
